### ISSUE TITLE
Scraping don't work on rke2?

### ISSUE THREAD

**Issue by tburschka** [olxbr/metrics-server-exporter#49]
Hi, 

i setup this via 

```
helm upgrade --install --namespace kube-system --set image.tag=v0.0.7  metrics-server-exporter ./helm
```

It seems to be functional, since the expected metrics show up, if i use port forward to the deployment.

Addionally i setup an ServiceMontior (my prometheus is running under `kube-telemetry`:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-server-exporter
  namespace: kube-telemetry
  labels:
    name: metrics-server-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: metrics-server-exporter
      app.kubernetes.io/name: metrics-server-exporter
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: "8000"
```

But even with the servicemonitor no metrics show up in prometheus
